
network.host: 0.0.0.0

xpack.security.enabled: false
xpack.license.self_generated.type: trial
xpack.monitoring.collection.enabled: false
discovery.type: single-node

cluster.routing.allocation.disk.threshold_enabled: false
cluster.routing.allocation.disk.watermark.flood_stage: 200mb
cluster.routing.allocation.disk.watermark.low: 500mb
cluster.routing.allocation.disk.watermark.high: 300mb