// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"awesomeProject/global"
	"awesomeProject/src/controller"
	"awesomeProject/src/repository/impl"
	impl2 "awesomeProject/src/service/impl"
	"database/sql"
)

// Injectors from user.di.go:

func InitUserRouterHanldel() (*controller.UserController, error) {
	iUserRepo := impl.NewUserRepoImpl()
	iUserService := impl2.NewUserServiceImpl(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}

// user.di.go:

func ProvideDB() *sql.DB {
	return global.Mdbcc
}
