version: '3.2'

networks:
  elk:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./elk/logger/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk

  kibana:
    image: kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk/logger/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.17.10
    container_name: logstash
    volumes:
      - ./elk/logger/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk/logger/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5045:5045"
      - "5001:5000/tcp"
      - "5024:5000/udp"
      - "9603:9600"
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch
    networks:
      - elk
